homepage <- dashboardPage(
  dashboardHeader(disable = T),
  dashboardSidebar(disable = T),
  dashboardBody(
    column(
      width = 10,
      offset = 1,
      titleBox("TPmp: miRNAs and phasiRNAs of Tea Plants")
    ),
    column(
      width = 10,
      offset = 1,
      textBox(
        width = 12,
        p("The miRNAs and phasiRNAs of Tea Plants (", em("Camellia sinensis"), ") (TPmp) is an interactive web application with multiple analysis modules developed to visualize and explore miRNA and phasiRNA in tea plants based on 81 sRNA-seq samples and 10 degradome-seq samples in NCBI.")
        )
      ),
    column(
      width = 10,
      offset = 1,
      sectionBox(
        title = "What's Inside",
        fluidRow(
          valueBox("952", "MIRNAs", width = 4),
          valueBox("427", "21nt and 24 nt phasiRNA", color = "purple", width = 4),
          valueBox("1782", "miRNA-target pairs", color = "yellow", width = 4)
          ),
        fluidRow(
          valueBox("2", "Small tools", color = "olive", width = 4),
          valueBox("83", "sRNA samples", color = "fuchsia", width = 4),
          valueBox("10", "Degradome samples", color = "navy", width = 4)
          
          )
        )
      ),
    column(
      width = 10,
      offset = 1,
      sectionBox(
        title = "Analysis Modules",
        messageBox(
          width = 12,
          p("We here present 5 modules to retrieve and analyze the miRNAs and phasiRANs dataset. Within each module, the user can select different parameters to retrieve and analyze. You can find some example figures that these modules can generate."),
          fluidRow(
            module_Box(
              width = 6,
              title = "miRNAs",
              imgSrc = "img/miRNA.png",
              text='"This module can display: ",br(),"(1) The position and secondary structure of pre-miRNA, ",br(),"(2) The target gene information of miRNA, ",br(),"(3) The expression of miRNA, ",br(),"(4) The regulation element on the promoter of pre-miRNA. ",br(),br(),"You can also download these information."'
              ),
            module_Box(
              width = 6,
              title = "phasiRNA",
              imgSrc = "img/phasiRNA.png",
              text = '"This module can display: ",br(),"(1) The position and phasing score of PHAS gene,",br(),"(2) The miRNA trigger of PHAS gene,",br(),"(3) The expression of phasiRNA.",br(),br(),"You can also download these information."'
              )
            ),
          fluidRow(
            module_Box(
              width = 6,
              title = "hcsiRNA",
              imgSrc = "img/hcsiRNA.png",
              text = '"This module can display:",br(),"The information of hcsiRNA, such as position and library number.",br(),br(),"You can also download these information."'
              ),
            module_Box(
              width = 6,
              title = "Extraction",
              imgSrc = "img/extraction.png",
              text = '"This module can display:",br(),"The information of the miRNAs contained in regions of the genome you have selected.",br(),br(),"You can also download these information."'
              )
            ),
          fluidRow(
            module_Box(
              width = 6,
              title = "Small tools",
              imgSrc = "img/tools.png",
              text = '"This module provides some useful tools:",br(),"(1) The tool for displaying miRNAs and targets by the files of users,",br(),"(2) The tool for display heatmap,",br(),"...",br(),br(),"You can also download these figures generated by these tools."'
             )
           )
          )
        )
      ),
    fluidRow(
      column(
        width = 10,
        offset = 1,
        box(
          title = "More about of TPmp",
          width = 12,
          solidHeader = TRUE,
          collapsible = TRUE,
          status = "warning",
          includeMarkdown("www/md/home.md")
          )
        )
      )
    
    )
  )
